### ISSUE TITLE
Move user password validation logic from repository to service

### ISSUE THREAD

**Issue by interestIngc** [globe-and-citizen/layer8#110]
Move logic related to salt generation and password hashing to the service from the repository, so that repository would only manage database interactions: https://github.com/globe-and-citizen/layer8/blob/0c622b018a0389db8df00974118136f8049f3493/server/resource_server/repository/repository.go#L26C1-L28C1

**Comment by stravid87** [comment]
I feel like this is relevant to a comment I made on the ZK PR

See `server/resource_server/emails/verification/zk/circuit/mimc_circuit.go` , Line 28.

Without adding the salt, anyone could spoof our implementation especially given that it is open source. Without knowing their salt, they cannot. Eventually though, we will need to improve on the source of the salt because to do SCRAM (Salted Challenge Response Authentication Mechanism), we actually SEND them their salt... obviously a problem in the long run. For now, a non-issue.
