### ISSUE TITLE
INTERCEPTOR: up_JWT expiration times? Also, should this be encrypted?

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/layer8#22]

**Comment by huzaifamk** [comment]
The JWT expiration time is here: https://github.com/globe-and-citizen/layer8/blob/development/server/utils/utils.go#L34

Currently it is 7 days, because we have been doing testing, but we can adjust it's value in the code.

And for the encryption of TOKENs, in future (Reference Issue: https://github.com/globe-and-citizen/layer8/issues/56) it will go the same way like we are doing for the keys, encrypted in the body.
