### ISSUE TITLE
INTERCEPTOR: Should we put JWTs & keys and & others in cookies?

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/layer8#24]

**Comment by huzaifamk** [comment]
I think this is not needed, because the Frontend does not have to store the Keys, and the JWTs anywhere, because everything is being hold in the interceptor, so some of good points to note here are:

- The keys are not exposed to the Frontend (Client-Side)
- Same is happening for the JWTs also, not being exposed to the Client
- There is no need to using the Local Storage or Cookies because the Frontend is not getting anything
- The Keys and the JWTs are stored inside the WASM Interceptor, so even the user itself can hardly access it by any means so this looks good according to security point of view
- Each user has his own copy of the WASM Interceptor so holding keys inside the WASM is not a problem and is working fine as tested (As I presented access from different browsers in a meeting and now the keys works fine, see commits:
- https://github.com/globe-and-citizen/layer8/commit/6df9a16e979b6400ec62ef4357167f079779cf1b
- https://github.com/globe-and-citizen/layer8/commit/dc4f2177b65e2702d05b393abce2d7d1c81dde75
- https://github.com/globe-and-citizen/layer8/commit/fccbb118adb3aef444da6be125551ef11f440b1e
)

**Comment by stravid87** [comment]
Good points.
After reading this answer, I think I might be confusing JWTs from Layer8 with the local storage calls of the frontend / backend VueJS SPA:

```
const SpToken = ref(localStorage.getItem("SP_TOKEN") || null);
const L8Token = ref(localStorage.getItem("L8_TOKEN") || null);
```

These, in the end, we won't have control over because it will be up to the service provider to do what they want on either side of L8

**Comment by huzaifamk** [comment]
Agreed 💯
