### ISSUE TITLE
Parsing Vs. Serving VueJS files from Go Templates

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/layer8#5]
Using `{{ }}` in go templates is problamatic.

from Go, 
```
t, err := template.ParseFiles("assets-v1/templates/homeView.html")
if err != nil {
http.Error(w, err.Error(), http.StatusInternalServerError)
return
}
```
This will error out if the handlebar notation (i.e., "{{}}" is used because the parser is trying to interpret it WITHOUT running vue.js )

on the other hand, 

```
var relativePathIndex = "assets-v1/templates/homeView.html"
indexPath := filepath.Join(utils.WorkingDirectory, relativePathIndex)
fmt.Println("indexPath: ", indexPath)
http.ServeFile(w, r, indexPath)
```

This works because here go is simply serving the raw file without parsing it. 

The challenge comes when you need to pass in a variable into the template (i.e., parse it) AND also serve it.

**Comment by stravid87** [comment]
This error is evident by commenting / uncommenting ClientHandler of `server\resource_server\controller\controller.go`

```
func ClientHandler(w http.ResponseWriter, r *http.Request) {

	if r.Method != http.MethodGet {
		w.WriteHeader(http.StatusMethodNotAllowed)
		fmt.Fprintln(w, http.StatusText(http.StatusMethodNotAllowed))
		return
	}

	utils.GetPwd()

	var relativePathUser = "assets-v1/templates/registerClient.html"
	userPath := filepath.Join(utils.WorkingDirectory, relativePathUser)
	fmt.Println("userPath: ", userPath)
	http.ServeFile(w, r, userPath)

	// load the registerClient page
	// t, err := template.ParseFiles("assets-v1/templates/registerClient.html")
	// if err != nil {
	// 	http.Error(w, err.Error(), http.StatusInternalServerError)
	// 	return
	// }

	// t.Execute(w, map[string]interface{}{
	// 	"ProxyURL": os.Getenv("PROXY_URL"),
	// })
}
```

**Comment by ternakkode** [comment]
Hi @stravid87, I don't see any issues while rendering HTML code and parsing variables to it without using VueJS. Here's the code example: [Commit](https://github.com/globe-and-citizen/layer8_temp/commit/882d70f3bc220e759a409f0d85837b2dd9767f91).

Here's how to test it:

1. Log in.
2. Access localhost/5001/user.

**Comment by ternakkode** [comment]
If you want to render a variable from the Golang code while moving to another page using VueJS, it's not doable. This is because the Golang code requires interaction with the server side, but the process in VueJS happens within the browser without interacting with the server. The variable from the Golang code will be parsed if you refresh the page because in this process, there will be interaction with the server side.

The most suitable solution that I proposed is completely separating the frontend side and backend side. We can compile VueJS code into HTML, CSS, and JS code, then deploy it to AWS S3 with very low cost and reliable performance. Any interaction with the backend side can be done via REST API.

**Comment by huzaifamk** [comment]
PR from @ternakkode : https://github.com/globe-and-citizen/layer8/pull/10, approved.
