### ISSUE TITLE
Error Handling in the Interceptor

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/layer8#6]
Currently, if the Interceptor errors out, it crashes the module. This can happen due to an error from the L8Proxy or the Service Provider.
Robust error handling will be necessary to protect the encrypted tunnel once it is built up. 
![layer8_fetch_errors](https://github.com/globe-and-citizen/layer8/assets/116566901/96e98e20-1959-458f-98c2-f5a0a8fd4a16)

**Comment by huzaifamk** [comment]
@stravid87 the promise that we are doing in the interceptor, i.e.

```
promise := js.Global().Get("Promise").New(js.FuncOf(func(this js.Value, args []js.Value) interface{} {
go func() {
.
.
.
.
}()
return nil
}), js.FuncOf(func(this js.Value, args []js.Value) interface{} {
return args[0].String()
}))
return promise
```

Does this not solve the issue 

> Go program has already exited

**Comment by huzaifamk** [comment]
@stravid87 I have also faced similar issue with the `fetch` function which is based on `promise`.

If you see my functions of `initializeECDHTunnel`, I am not using a promise there and that handles error fine when an error occurs, the Go program does not exit because when there is an error, I take the log, and return the function and not to continue forward because if it continue, the whole program is going to break, we need to do more experiments here!

**Comment by stravid87** [comment]
Yes agreed about doing experiments. However, I think that we need the promises because fetch returns a promise and I want to be consistent. In my repo, https://github.com/stravid87/ecdh_attempt.git, I found that anywhere err != nil, I could call reject. 
i.e., `reject.Invoke(js.ValueOf(err.Error()))`
This also seemed effective.

**Comment by huzaifamk** [comment]
Yes promise is necessary and works well, and this: `reject.Invoke(js.ValueOf(err.Error()))` is also a good idea to handle the errors.

**Comment by stravid87** [comment]
This issue has gone stale and is best dealt with error by error (which is occurring already).
See #49 
As error arise, i will open more issues.
